apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ssso9fp35-go 
  janus-idp.io/tekton: ssso9fp35-go
  backstage.io/kubernetes-id: ssso9fp35-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ssso9fp35-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  