apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ssso9fp35-go-gitops
  description: This is GitOps manifest for ssso9fp35-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: ssso9fp35-go
    janus-idp.io/tekton: ssso9fp35-go
    backstage.io/kubernetes-id: ssso9fp35-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ssso9fp35-go
